spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cache:
    type: simple

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

server:
  port: 8080

logging:
  level:
    com.innowise.userService: DEBUG
    org.hibernate.SQL: DEBUG